### ISSUE TITLE
DRS 1.2 spec does not include version number

### ISSUE THREAD

**Issue by ianfore** [ga4gh/drs-compliance-suite#35]
The Swagger version of the DRS spec does not list 'version' as a requirement.
 https://editor.swagger.io/?url=https://ga4gh.github.io/data-repository-service-schemas/preview/release/drs-1.2.0/openapi.yaml

This is a possible issue because the compliance suite apparently relies on version to determine which checks to perform.

**Comment by yash-puligundla** [comment]
The current drs-compliance-suite version (v1.2.0) does not rely on service-info response for the DRS version. This change has been made to allow existing implementations without service-info to still be able to use the compliance-suite.

As per DRS v1.2.0, "type" field is required in the service-info response. "version" field is required in the "type" object. (Please refer to the attached screenshot from the swagger document linked above)
<img width="862" alt="image" src="https://user-images.githubusercontent.com/89084962/233463955-b02a10d2-21a8-4ab0-b0ce-78cbf6865cb4.png">
