### ISSUE TITLE
Add unittests to test the service-info, get object tests and report generation for good_mock server

### ISSUE THREAD

**Issue by yash-puligundla** [ga4gh/drs-compliance-suite#7]

**Comment by emre-f** [comment]
For this issue, would the mock server be already running or should I write a command that spins up the mock server, run the tests and then shut it down?

**Comment by yash-puligundla** [comment]
Let's start with manually running and shutting down the mock servers. Later, we can add a Makefile with different commands.

**Comment by emre-f** [comment]
This has been completed with this [pull request](https://github.com/ga4gh/drs-compliance-suite/pull/13)
